image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: testCI.sln
  verbosity: minimal
  
environment:
    COVERALLS_REPO_TOKEN:  
       secure: wgwH1Q4qJs6CisALwyeQ6n1ZrEfXz8qI4

after_test: 
    - C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"%programfiles(x86)%\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:testCI.Tests.dll" -output:coverage.xml
        
    - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml